#ifndef ENUMS
#define ENUMS

enum toolsID {
	TOOLS_ID_FREEHAND, 
	TOOLS_ID_LINE, 
	TOOLS_ID_RECTANGLE,
	TOOLS_ID_CIRCLE, 
	TOOLS_ID_POLYGON, 
	TOOLS_ID_TEXT, 
};

enum colorsID {
	COLOR_BLUE, 
	COLOR_BLACK, 
	COLOR_RED,
	COLOR_GREEN, 
	COLOR_YELLOW,
};

enum menusID{
	FILE_MENU_ID_NEW,
	FILE_MENU_ID_OPEN, 
	FILE_MENU_ID_SAVE, 
	FILE_MENU_ID_SAVE_AS,
	TOOLS_MENU_ID_FREEHAND, 
	TOOLS_MENU_ID_LINE, 
	TOOLS_MENU_ID_CIRCLE, 
	TOOLS_MENU_ID_RECTANGLE,
	TOOLS_MENU_ID_POLYGON, 
	TOOLS_MENU_ID_TEXT, 
	STYLE_MENU_ID_PEN, 
	STYLE_MENU_ID_BRUSH, 
	STYLE_MENU_ID_FONT
};

#endif

